routes/web.php
<?php

use App\Http\Controllers\AgendaController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LampuController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SaranController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login-process', [AuthController::class, 'loginProcess'])->name('login.process');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('/users', UserController::class);
    Route::resource('/laporan', LaporanController::class);
    Route::resource('/lampu', LampuController::class);
    Route::resource('/petugas', PetugasController::class);
    Route::resource('/agenda', AgendaController::class);
    Route::resource('/slider', SliderController::class);



    Route::get('/role', [RoleController::class, 'index'])->name('role.index');
    Route::get('/role/create', [RoleController::class, 'create'])->name('role.create');
    Route::post('/role', [RoleController::class, 'store'])->name('role.store');
    Route::get('/role/{id}/edit', [RoleController::class, 'edit'])->name('role.edit');
    Route::put('/role/{id}/update', [RoleController::class, 'update'])->name('role.update');

    Route::get('/saran', [SaranController::class, 'index'])->name('saran.index');
    Route::get('/saran/create', [SaranController::class, 'create'])->name('saran.create');
    Route::post('/saran', [SaranController::class, 'store'])->name('saran.store');
    Route::get('/saran/{id}/update', [SaranController::class, 'delete'])->name('role.delete');



    // DELETE ROUTE
    Route::get('/user/{id}/delete', [UserController::class, 'delete'])->name('users.delete');
    Route::get('/saran/{id}/delete', [SaranController::class, 'delete'])->name('saran.delete');
    //     Route::get('/lampu/read/file', [LampuController::class, 'readCsv'])->name('lampu.read');
    // Route::get('/laporan/{id}/delete', [LaporanController::class, 'delete'])->name('laporan.delete');

    // CUSTOM ROUTER FOR PUT / PATCH IMAGE FORM
    Route::post('/laporan/{id}/updateImage', [LaporanController::class, 'updateImage'])->name('laporan.updateImage');


    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});

app/Models/Agenda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AgendaStoreRequest;
use App\Http\Requests\AgendaUpdateRequest;
use App\Services\Agenda\AgendaServiceInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class AgendaController extends Controller
{
    protected AgendaServiceInterface $agendaService ;

    /**
     * @param AgendaServiceInterface $agendaService
     */
    public function __construct(AgendaServiceInterface $agendaService)
    {
        $this->agendaService = $agendaService;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if (!Auth::user()->can('read agenda')) abort(403);
        $agendas = $this->agendaService->getAll();
        return view('agenda.index', ['agendas' => $agendas]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        if (!Auth::user()->can('create agenda')) abort(403);
        return view('agenda.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(AgendaStoreRequest $request)
    {
        if (!Auth::user()->can('create agenda')) abort(403);
        $validatedRequest = $request->safe()->except(['_token']);

        try {
            $this->agendaService->insert($validatedRequest);
            return redirect()->route('agenda.index')->with('message', "Agenda berhasil dibuat.");
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['request' => $validatedRequest]);
            return redirect()->route('agenda.index')->with('error', "Agenda gagal dibuat.");
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        if (!Auth::user()->can('update agenda')) abort(403);

        $agenda = $this->agendaService->getById($id);
        return view('agenda.edit', ['agenda' => $agenda]);

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(AgendaUpdateRequest $request, string $id)
    {
        if (!Auth::user()->can('update agenda')) abort(403);
        $validatedRequest = $request->safe()->except(['_token']);
        try {
            $this->agendaService->update($id, $validatedRequest);
            return redirect()->route('agenda.index')->with('message', "Agenda berhasil diubah.");
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['request' => $validatedRequest]);
            return redirect()->route('agenda.index')->with('error', "Agenda gagal diubah.");
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        if (!Auth::user()->can('delete agenda')) abort(403);

        try {
            $this->agendaService->delete($id);
            return redirect()->route('agenda.index')->with('message', "Agenda berhasil dihapus.");
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['id Agenda' => $id]);
            return redirect()->route('agenda.index')->with('error', "Agenda gagal dihapus.");
        }

    }
}

app/Http/Controllers/Api/AgendaController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\LaporanIndexRequest;
use App\Http\Resources\AgendaResource;
use App\Services\Agenda\AgendaServiceInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class AgendaController extends Controller
{
    public function __construct(protected AgendaServiceInterface $agendaService)
    {
    }


    public function index(LaporanIndexRequest $request)
    {

        try {

            if (isset($request->limit) && $request->limit != '') {
                $agenda =  AgendaResource::collection($this->agendaService->getLimit($request->limit));
            } else {
                $agenda =  AgendaResource::collection($this->agendaService->getAll());
            }

            return response()->json(
                [
                    'success' => true,
                    'message' => 'Agenda ditemukan.',
                    'data' => $agenda
                ],
                200
            );
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['context' => 'Failed Get Agenda Index']);
            return response()->json(
                [
                    'success' => false,
                    'message' => $th->getMessage(),
                    'data' => []
                ],
                500
            );
        }
    }

    public function show($id)
    {
        try {
            $agenda = $this->agendaService->getById($id);
            $agendaResponse = new AgendaResource($agenda);

            return response()->json(
                [
                    'success' => true,
                    'message' => 'agenda ditemukan.',
                    'data' => $agendaResponse,
                ],
                200
            );
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['context' => 'Failed Get agenda detail']);
            return response()->json(
                [
                    'success' => false,
                    'message' => $th->getMessage(),
                    'data' => []
                ],
                500
            );
        }
    }
}

resources/views/agenda/create.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Tambah Agenda')
@section('page-heading')
    <h1>Tambah Agenda</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item"><a href="{{route('saran.index')}}">Agenda</a></div>
        <div class="breadcrumb-item">Tambah Agenda</div>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $err)
                            <div class="alert alert-danger">
                                {{$err}}
                            </div>
                        @endforeach
                    @endif
                    <form action="{{route('agenda.store')}}" class="form" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row mb-2">
                            <label for="judul" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Judul Agenda</label>
                            <div class="col-sm-12 col-md-6">
                                <input type="text" id="judul" name="judul" class="form-control" value="{{old('judul')}}" required>
                            </div>
                        </div>
                        <div class="form-group row mb-2">
                            <label for="deskripsi" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Deskripsi Agenda</label>
                            <div class="col-sm-12 col-md-4">
                                <textarea class="form-control" name="deskripsi" id="deskripsi" style="height: 300px">{{old('deskripsi')}}</textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-2">
                            <label for="foto" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Foto Agenda</label>
                            <div class="col-sm-12 col-md-2">
                                <input type="file" id="foto" name="foto" class="form-control" value="{{old('foto')}}" required>
                            </div>
                        </div>


                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/agenda/edit.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Edit Agenda')
@section('page-heading')
    <h1>Edit Agenda</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item"><a href="{{route('saran.index')}}">Agenda</a></div>
        <div class="breadcrumb-item">Edit </div>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $err)
                            <div class="alert alert-danger">
                                {{$err}}
                            </div>
                        @endforeach
                    @endif
                    <form action="{{route('agenda.update', $agenda->id)}}" class="form" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group row mb-2">
                            <label for="judul" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Judul Agenda</label>
                            <div class="col-sm-12 col-md-6">
                                <input type="text" id="judul" name="judul" class="form-control" value="{{old('judul') ?? $agenda->judul}}" required>
                            </div>
                        </div>
                        <div class="form-group row mb-2">
                            <label for="deskripsi" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Deskripsi Agenda</label>
                            <div class="col-sm-12 col-md-4">
                                <textarea class="form-control" name="deskripsi" id="deskripsi" style="height: 300px">{{old('deskripsi') ?? $agenda->deskripsi}}</textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-2">
                            <label for="foto" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Foto Agenda</label>
                            <div class="col-sm-12 col-md-2">
                                <input type="file" id="foto" name="foto" class="form-control" value="{{old('foto') ?? $agenda->foto}}">
                                <img src="{{asset('uploads'. '/'.$agenda->foto)}}" class="img-preview img-thumbnail mt-2" alt="{{$agenda->foto}}">

                            </div>
                        </div>


                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('page-css')
@endpush

@push('page-js')
    <script>
        $('#foto').change(function(){
            let reader = new FileReader();

            reader.onload = (e) => {

                $('.img-preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(this.files[0]);
        })
    </script>
@endpush

resources/views/agenda/index.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Agenda')
@section('page-heading')
    <h1>Agenda</h1>
@endsection
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body table-responsive">
                    <a href="{{route('agenda.create')}}" class="btn btn-info mb-2">Tambah Data</a>
                    @if (session('error'))
                        <div class="alert alert-danger">{{session('error')}}</div>
                    @endif
                    @if (session('message'))
                        <div class="alert alert-primary">{{session('message')}}</div>
                    @endif
                    <table class="table table-hover datatable">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Judul Agenda</th>
                            <th>Deskripsi Agenda</th>
                            <th>Foto</th>
                            <th style="width: 120px">Created at</th>
                            <th style="width: 50px">action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php $no =1; @endphp
                        @foreach ($agendas as $agenda)
                            <tr>
                                <td>{{$no++}}</td>
                                <td>{{substr($agenda->judul, 0,150)}}</td>
                                <td>{{substr($agenda->deskripsi, 0,150)}}...</td>
                                <td><img class="img-thumbnail" src="{{asset('uploads') .'/'. $agenda->foto}}" alt="{{$agenda->foto}}" style="height: 100px"></td>
                                <td>{{$agenda->created_at}}</td>
                                <td>
                                    <a href="{{route('agenda.edit', $agenda->id)}}" class="btn btn-icon btn-sm btn-warning"><i class="fas fa-edit"></i></a>
                                    <a data-toggles="modal" id="smallButton" data-target="#deleteModal" data-action="{{route('agenda.destroy', $agenda->id)}}" class="btn btn-icon btn-sm btn-danger btn-fire" href="#"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('modal')
    <div class="modal fade" tabindex="-1" role="dialog" id="deleteModal" aria-hidden="true" style="display: none;">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="" method="POST" id="formDelete">
                    @csrf
                    @method('DELETE')
                    <div class="modal-header">
                        <h5 class="modal-title">Konfirmasi Hapus Data</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Apakah Anda yakin menghapus data ? </p>
                    </div>
                    <div class="modal-footer bg-whitesmoke br">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endpush

@push('page-css')
    <link rel="stylesheet" href="{{asset('assets/modules/DataTables/dt/css/dataTables.bootstrap4.min.css')}}">
@endpush
@push('page-js')
    <script src="{{asset('assets/modules/DataTables/dt/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/modules/DataTables/dt/js/dataTables.bootstrap4.min.js')}}"></script>
    <script>
        $(document).ready( function () {
            $('.datatable').DataTable();
        });

        // delete handle
        $('.btn-fire').click(function(){
            $('#deleteModal').modal({ backdrop: 'static', keyboard: false })
            $('#formDelete').attr('action', $(this).data('action'))
        })

        $('#deleteModal').on('hidden.bs.modal', function (e) {
            $('#formDelete').attr('action', '')
            console.log(e);
        })
    </script>
@endpush