routes/web.php
<?php

use App\Http\Controllers\AgendaController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LampuController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SaranController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login-process', [AuthController::class, 'loginProcess'])->name('login.process');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('/users', UserController::class);
    Route::resource('/laporan', LaporanController::class);
    Route::resource('/lampu', LampuController::class);
    Route::resource('/petugas', PetugasController::class);
    Route::resource('/agenda', AgendaController::class);
    Route::resource('/slider', SliderController::class);



    Route::get('/role', [RoleController::class, 'index'])->name('role.index');
    Route::get('/role/create', [RoleController::class, 'create'])->name('role.create');
    Route::post('/role', [RoleController::class, 'store'])->name('role.store');
    Route::get('/role/{id}/edit', [RoleController::class, 'edit'])->name('role.edit');
    Route::put('/role/{id}/update', [RoleController::class, 'update'])->name('role.update');

    Route::get('/saran', [SaranController::class, 'index'])->name('saran.index');
    Route::get('/saran/create', [SaranController::class, 'create'])->name('saran.create');
    Route::post('/saran', [SaranController::class, 'store'])->name('saran.store');
    Route::get('/saran/{id}/update', [SaranController::class, 'delete'])->name('role.delete');



    // DELETE ROUTE
    Route::get('/user/{id}/delete', [UserController::class, 'delete'])->name('users.delete');
    Route::get('/saran/{id}/delete', [SaranController::class, 'delete'])->name('saran.delete');
    //     Route::get('/lampu/read/file', [LampuController::class, 'readCsv'])->name('lampu.read');
    // Route::get('/laporan/{id}/delete', [LaporanController::class, 'delete'])->name('laporan.delete');

    // CUSTOM ROUTER FOR PUT / PATCH IMAGE FORM
    Route::post('/laporan/{id}/updateImage', [LaporanController::class, 'updateImage'])->name('laporan.updateImage');


    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});

app/Models/Laporan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Laporan extends Model
{
    use HasFactory;
    protected $primaryKey = 'idLaporan';
    protected $guarded = [];
}

app/Http/Controllers/Api/LaporanController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Controllers\LaporanController as ControllersLaporanController;
use App\Http\Requests\LaporanDeleteRequest;
use App\Http\Requests\LaporanIndexRequest;
use App\Http\Requests\LaporanStoreRequest;
use App\Http\Resources\LaporanCollection;
use App\Http\Resources\LaporanResource;
use App\Models\Laporan;
use App\Services\Laporan\LaporanServiceInterface;
use App\Services\Petugas\PetugasServiceInterface;
use Exception;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class LaporanController extends Controller
{
    private $laporanService;

    public function __construct(LaporanServiceInterface $laporanService, private PetugasServiceInterface $petugasService)
    {
        $this->laporanService = $laporanService;
    }

    public function index(LaporanIndexRequest $request)
    {

        try {

            if (isset($request->limit) && $request->limit != '') {
                $laporan =  LaporanResource::collection($this->laporanService->getLimit($request->limit));
            } else {
                $laporan =  new LaporanCollection($this->laporanService->getAllPaginated());
            }

            return response()->json(
                [
                    'success' => true,
                    'message' => 'Laporan ditemukan.',
                    'data' => $laporan
                ],
                200
            );
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['context' => 'Failed Get Laporan Index']);
            return response()->json(
                [
                    'success' => false,
                    'message' => $th->getMessage(),
                    'data' => []
                ],
                500
            );
        }
    }

    public function store(LaporanStoreRequest $request)
    {
        $validRequest = $request->validated();

        try {
            $token = 'tokenku123987347@1234';

            if ($request->header('token') !== $token) {
                throw new \Exception('Token invalid', 1);
            }

            $laporan = $this->laporanService->store($validRequest);

            return response()->json(
                [
                    'success' => true,
                    'message' => 'Sukses membuat laporan.',
                    'data' => $laporan
                ],
                200
            );
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['request' => $validRequest]);
            return response()->json(
                [
                    'success' => false,
                    'message' => $th->getMessage(),
                    'data' => []
                ],
                500
            );
        }
    }

    public function show($id)
    {
        try {
            $laporan = $this->laporanService->getById($id);
            $laporanResponse = new  LaporanResource($laporan);
            $petugas = ControllersLaporanController::getPetugas($laporan->petugas, $this->petugasService);

            return response()->json(
                [
                    'success' => true,
                    'message' => 'Laporan ditemukan.',
                    'data' => $laporanResponse,
                    'petugas' => $petugas
                ],
                200
            );
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['context' => 'Failed Get Laporan detail']);
            return response()->json(
                [
                    'success' => false,
                    'message' => $th->getMessage(),
                    'data' => []
                ],
                500
            );
        }
    }

    public function delete($id, LaporanDeleteRequest $request)
    {
        try {

            $validRequest = $request->validated();

            $laporan = $this->laporanService->getById($id);

            if ($validRequest['noHp'] !== $laporan->noHp) {
                throw new \Exception("No HP tidak cocok dengan laporan.", 1);
            }

            $this->laporanService->delete($id);

            return response()->json(
                [
                    'success' => true,
                    'message' => 'Laporan dihapus.',
                    'data' => []
                ],
                200
            );
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['context' => 'Failed Delete Laporan']);
            return response()->json(
                [
                    'success' => false,
                    'message' => $th->getMessage(),
                    'data' => []
                ],
                500
            );
        }
    }

    public function getTotalGroupByMonth()
    {


        try {
            $laporan = DB::table('laporans')->select(
                DB::raw("(count(idLaporan)) as total_laporan"),
                DB::raw("(DATE_FORMAT(created_at, '%M')) as month"),
                DB::raw("cast((DATE_FORMAT(created_at, '%c')) as signed)  as bulan")
            )
                ->orderBy('bulan', 'asc')
                ->groupBy('month')
                ->groupBy('bulan')
                ->get();

            return response()->json(
                [
                    'success' => true,
                    'message' => 'Statictic Laporan Calculated.',
                    'data' => $laporan
                ],
                200
            );
        } catch (\Throwable $th) {
            Log::error($th->getMessage(), ['context' => 'Failed Get Stats Laporan']);
            return response()->json(
                [
                    'success' => false,
                    'message' => $th->getMessage(),
                    'data' => []
                ],
                500
            );
        }
    }
}

app/Http/Controllers/LaporanController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LaporanStoreRequest;
use App\Http\Requests\LaporanUpdateRequest;
use App\Services\Laporan\LaporanServiceInterface;
use App\Services\Petugas\PetugasServiceInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class LaporanController extends Controller
{
    private $laporanService;
    private $petugasService;

    public function __construct(LaporanServiceInterface $laporanService, PetugasServiceInterface $petugasService)
    {
        $this->laporanService = $laporanService;
        $this->petugasService = $petugasService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if (!Auth::user()->can('read laporan')) abort(403);

        $laporans = $this->laporanService->getAll();
        return view('laporan.index', ['laporans' => $laporans]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        if (!Auth::user()->can('create laporan')) abort(403);

        return view('laporan.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(LaporanStoreRequest $request)
    {
        if (!Auth::user()->can('create laporan')) abort(403);

        $validRequest = $request->safe()->except(['_token']);

        try {
            $this->laporanService->store($validRequest);
            return redirect()->route('laporan.index')->with('message', "Laporan berhasil dibuat.");
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['request' => $validRequest]);
            return redirect()->route('laporan.index')->with('error', "Laporan gagal dibuat.");
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        if (!Auth::user()->can('read laporan')) abort(403);

        $laporan = $this->laporanService->getById($id);

        $petugas = self::getPetugas($laporan->petugas, $this->petugasService);

        return view('laporan.detail', ['laporan' => $laporan, 'petugas' => $petugas]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        if (!Auth::user()->can('update laporan')) abort(403);

        $laporan = $this->laporanService->getById($id);
        $petugas = $this->petugasService->getAll();

        return view('laporan.edit', ['laporan' => $laporan, 'petugas' => $petugas]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function updateImage(LaporanUpdateRequest $request, string $id)
    {
        if (!Auth::user()->can('update laporan')) abort(403);

        $validRequest = $request->safe()->except(['_token']);
        // dd($validRequest);
        try {
            $this->laporanService->update($id, $validRequest);
            return redirect()->route('laporan.index')->with('message', "Laporan berhasil diubah.");
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['request' => $validRequest]);
            return redirect()->route('laporan.index')->with('error', "Laporan gagal diubah.");
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        if (!Auth::user()->can('delete laporan')) abort(403);

        try {
            $this->laporanService->delete($id);
            return redirect()->route('laporan.index')->with('message', "Laporan berhasil dihapus.");
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['id Laporan' => $id]);
            return redirect()->route('laporan.index')->with('error', "Laporan gagal dihapus.");
        }
    }

    public static function getPetugas(?string $petugasId,  PetugasServiceInterface $petugasService)
    {
        $petugas = [];

        if ($petugasId && $petugasId !== '' && $petugasId !== null) {
            $petugasId = json_decode($petugasId);

            for ($i = 0; $i < count($petugasId); $i++) {
                $petugas_row = $petugasService->getById($petugasId[$i]);
                $petugas[] = $petugas_row;
            }
        }

        return $petugas;
    }
}

resources/views/laporan/create.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Buat Laporan')
@section('page-heading')
  <h1>Buat laporan</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item"><a href="{{route('laporan.index')}}">Laporan</a></div>
    <div class="breadcrumb-item">Buat Laporan</div>
  </div>
@endsection
@section('content')
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
          @if ($errors->any())
            @foreach ($errors->all() as $err)
              <div class="alert alert-danger">
                  {{$err}}
              </div>
            @endforeach
          @endif
        <form action="{{route('laporan.store')}}" class="form" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="form-group row mb-2">
            <label for="namaPelapor" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama Pelapor</label>
            <div class="col-sm-12 col-md-2">
              <input type="text" id="namaPelapor" name="namaPelapor" class="form-control" value="{{old('namaPelapor')}}" required>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label for="keterangan" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Keterangan</label>
            <div class="col-sm-12 col-md-4">
                <textarea name="keterangan" id="keterangan" class="form-control" style="height: 80px">{{old('keterangan')}}</textarea>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label for="alamat" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">alamat</label>
            <div class="col-sm-12 col-md-4">
                <textarea name="alamat" id="alamat" class="form-control" style="height: 80px">{{old('alamat')}}</textarea>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label for="latitude" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Latitude</label>
            <div class="col-sm-12 col-md-2">
              <input type="text" id="latitude" name="latitude" class="form-control" value="{{old('latitude') ?? 0}}" required>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label for="longitude" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Longitude</label>
            <div class="col-sm-12 col-md-2">
              <input type="text" id="longitude" name="longitude" class="form-control" value="{{old('longitude') ?? 0}}" required>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label for="noHp" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">No HP</label>
            <div class="col-sm-12 col-md-2">
              <input type="text" id="noHp" name="noHp" class="form-control" value="{{old('noHp')}}" required>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label for="status" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Status</label>
            <div class="col-sm-12 col-md-2">
                <select id="status" name="status" class="form-control select2" required>
                    <option value="">--- Pilih Status ---</option>
                    <option value="1" selected>Ditinjau (masuk)</option>
                    <option value="2">Diproses</option>
                    <option value="3">Selesai</option>
                </select>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label for="gambar" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Gambar</label>
            <div class="col-sm-12 col-md-2">
              <input type="file" id="gambar" name="gambar" class="form-control" value="{{old('gambar')}}" required>
            </div>
          </div>
          <div class="form-group row mb-4">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
            <div class="col-sm-12 col-md-7">
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </div>
        </form>
        <a href="{{url()->previous()}}" class="btn btn-icon btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a>
      </div>
    </div>
  </div>
</div>
@endsection

@push('page-css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endpush

@push('page-js')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
  // In your Javascript (external .js resource or <script> tag)
$(document).ready(function() {
    $('.select2').select2();
});
</script>
@endpush

resources/views/laporan/detail.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Detail Laporan')
@section('page-heading')
  <h1>Detail Laporan</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item"><a href="{{route('laporan.index')}}">Laporan</a></div>
    <div class="breadcrumb-item">Detail Laporan</div>
  </div>
@endsection
@section('content')
<div class="row">
  <div class="col-12 col-md-6 col-lg-6">
    <div class="card card-primary">
        <div class="card-header">
            <h4>Data Pelapor</h4>
        </div>
        <div class="card-body">
            <div class="form-group row">
                <label class="col-form-label text-md-left col-12">Nama Pelapor</label>
                <div class="col-12 col-xl-6">
                    <input type="text" class="form-control" value="{{$laporan->namaPelapor}}" readonly>
                  </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-md-left col-12">No Handphone</label>
                <div class="col-12 col-xl-6">
                    <input type="text" class="form-control" value="{{$laporan->noHp}}" readonly>
                  </div>
            </div>
        </div>
    </div>

    <div class="card card-primary">
        <div class="card-header">
            <h4>Detail Laporan</h4>
        </div>
        <div class="card-body">
            <div class="form-group row">
                <label class="col-form-label text-md-left col-12">Keterangan</label>
                <div class="col-12">
                    <textarea class="form-control" style="height: 60px;" readonly>{{$laporan->keterangan}}</textarea>
                  </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-md-left col-12 ">Alamat</label>
                <div class="col-12">
                    <textarea class="form-control" style="height: 60px;" readonly>{{$laporan->alamat}}</textarea>
                  </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-md-left col-12 col-md-2 col-lg-2">Status</label>
                <div class="col-sm-12 col-md-8 col-lg-8">
                    @if ($laporan->status == 1)
                        <div class="badge badge-info">Ditinjau</div>
                    @elseif($laporan->status == 2)
                        <div class="badge badge-primary">Diproses</div>
                    @else
                        <div class="badge badge-success">Selesai</div>
                    @endif
                  </div> 
            </div>
            <div class="form-group row">
                <label for="" class="col-form-label text-md-left col-12 col-md-2 col-lg-2">Petugas</label>
                <div class="col-sm-2 col-md-8 col-lg-8">   
                    <ul class="list-group list-group-flush">
                        @foreach ($petugas as $p)
                            <li class="list-group-item"><a href="#" class="font-weight-600 mb-4"><img src="{{asset('assets')}}/img/avatar/avatar-1.png" alt="avatar" width="30" class="rounded-circle mr-1"> {{$p->nip .' - '.$p->namaPetugas}}</a></li>
                        @endforeach
                      </ul>
                </div>
            </div>
            <div id='map' style='width: 100%; height: 300px;'></div>
            <a href="{{url()->previous()}}" class="btn btn-icon btn-danger mt-4"><i class="fa fa-arrow-left"></i> Kembali</a>
        </div>
    </div>
  </div>

  <div class="col-12 col-md-6 col-lg-6">
    <div class="card card-primary">
        <div class="card-header">
            <h4>Gambar Laporan</h4>
        </div>
        <div class="card-body">
            <img src="{{asset('uploads'). '/' .$laporan->gambar}}" class="img-fluid img-thumbnail mb-4" alt="{{$laporan->idLaporan}}">
        </div>
    </div>
  </div>
</div>
@endsection

@push('page-css') 
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css' rel='stylesheet' />
@endpush

@push('page-js')
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.js'></script>  
    <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoieXVzaGFybmFkaSIsImEiOiJjbGp3YzVpeWgwb2FiM2luMXQwNjkzMW0yIn0.3CXh3GgHOJCbUhZgEyrAYA';
        const map = new mapboxgl.Map({
        container: 'map', // container ID
        style: 'mapbox://styles/mapbox/streets-v12', // style URL
        center: [{{$laporan->longitude .',' . $laporan->latitude }}], // starting position [lng, lat]
        zoom: 14, // starting zoom
        });

        // ADD USER PIN LOCATION 
        map.addControl(new mapboxgl.GeolocateControl({
            positionOptions: {
                enableHighAccuracy: true
            },
            trackUserLocation: true,
            showUserHeading: true
        }
        ));

        // ADD ZOOM BUTTON 
        const nav = new mapboxgl.NavigationControl({
            visualizePitch: true
        });

        map.addControl(nav, 'bottom-right');

        // Set marker options.
        const marker = new mapboxgl.Marker({
        color: "#F06292",
        draggable: true
        }).setLngLat([{{$laporan->longitude .',' . $laporan->latitude }}])
        .addTo(map);
        </script>
@endpush

resources/views/laporan/index.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Laporan')
@section('page-heading')
  <h1>Laporan</h1>
@endsection
@section('content')
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body table-responsive">
          <a href="{{route('laporan.create')}}" class="btn btn-primary mb-2">Tambah Data</a>
          @if (session('error'))
            <div class="alert alert-danger">{{session('error')}}</div>
          @endif
          @if (session('message'))
            <div class="alert alert-info">{{session('message')}}</div>
          @endif
          <table class="table table-hover datatable">
            <thead>
              <tr>
                <th style="width: 30px">ID#</th>
                <th>Nama</th>
                <th>Keterangan</th>
                <th>Alamat</th>
                <th>No HP</th>
                <th>Status</th>
                <th>Waktu</th>
                <th style="width: 90px">action</th>
              </tr>
            </thead>
            <tbody>
            @foreach ($laporans as $laporan)
                <tr>
                    <td>{{$laporan->idLaporan}}</td>
                    <td>{{$laporan->namaPelapor}}</td>
                    <td>{{$laporan->keterangan}}</td>
                    <td>{{$laporan->alamat}}</td>
                    <td>{{$laporan->noHp}}</td>
                    <td>
                      @if ($laporan->status == 1)
                        <div class="badge badge-info">Ditinjau</div>
                      @elseif($laporan->status == 2)
                          <div class="badge badge-primary">Diproses</div>
                      @else
                          <div class="badge badge-success">Selesai</div>
                      @endif
                    </td>
                    <td>{{$laporan->created_at}}</td>
                    <td>
                        <a href="{{route('laporan.show', $laporan->idLaporan)}}" class="btn btn-icon btn-sm btn-info"><i class="fas fa-eye"></i></a>
                        <a href="{{route('laporan.edit', $laporan->idLaporan)}}" class="btn btn-icon btn-sm btn-warning"><i class="fas fa-edit"></i></a>
                        <a data-toggles="modal" id="smallButton" data-target="#deleteModal" data-action="{{route('laporan.destroy', $laporan->idLaporan)}}" class="btn btn-icon btn-sm btn-danger btn-fire" href="#"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
@endsection

@push('modal')
  <div class="modal fade" tabindex="-1" role="dialog" id="deleteModal" aria-hidden="true" style="display: none;">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form action="" method="POST" id="formDelete">
          @csrf
          @method('DELETE')
        <div class="modal-header">
          <h5 class="modal-title">Konfirmasi Hapus Data</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Apakah Anda yakin menghapus data ? </p>
        </div>
        <div class="modal-footer bg-whitesmoke br">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-danger">Save changes</button>
        </div>
      </form>
      </div>
    </div>
  </div>
@endpush

@push('page-css')
  <link rel="stylesheet" href="{{asset('assets/modules/DataTables/dt/css/dataTables.bootstrap4.min.css')}}">
@endpush

@push('page-js')
  <script src="{{asset('assets/modules/DataTables/dt/js/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('assets/modules/DataTables/dt/js/dataTables.bootstrap4.min.js')}}"></script>
  <script>
    $(document).ready( function () {
      $('.datatable').DataTable({
        order: [[0, 'desc']]
      });

      $('.btn-fire').click(function(){
        $('#deleteModal').modal({ backdrop: 'static', keyboard: false })
        $('#formDelete').attr('action', $(this).data('action'))
      })

      $('#deleteModal').on('hidden.bs.modal', function (e) {
        $('#formDelete').attr('action', '')
        console.log(e);
      })
    });
  </script>
@endpush