routes/web.php
<?php

use App\Http\Controllers\AgendaController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LampuController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SaranController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login-process', [AuthController::class, 'loginProcess'])->name('login.process');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('/users', UserController::class);
    Route::resource('/laporan', LaporanController::class);
    Route::resource('/lampu', LampuController::class);
    Route::resource('/petugas', PetugasController::class);
    Route::resource('/agenda', AgendaController::class);
    Route::resource('/slider', SliderController::class);



    Route::get('/role', [RoleController::class, 'index'])->name('role.index');
    Route::get('/role/create', [RoleController::class, 'create'])->name('role.create');
    Route::post('/role', [RoleController::class, 'store'])->name('role.store');
    Route::get('/role/{id}/edit', [RoleController::class, 'edit'])->name('role.edit');
    Route::put('/role/{id}/update', [RoleController::class, 'update'])->name('role.update');

    Route::get('/saran', [SaranController::class, 'index'])->name('saran.index');
    Route::get('/saran/create', [SaranController::class, 'create'])->name('saran.create');
    Route::post('/saran', [SaranController::class, 'store'])->name('saran.store');
    Route::get('/saran/{id}/update', [SaranController::class, 'delete'])->name('role.delete');



    // DELETE ROUTE
    Route::get('/user/{id}/delete', [UserController::class, 'delete'])->name('users.delete');
    Route::get('/saran/{id}/delete', [SaranController::class, 'delete'])->name('saran.delete');
    //     Route::get('/lampu/read/file', [LampuController::class, 'readCsv'])->name('lampu.read');
    // Route::get('/laporan/{id}/delete', [LaporanController::class, 'delete'])->name('laporan.delete');

    // CUSTOM ROUTER FOR PUT / PATCH IMAGE FORM
    Route::post('/laporan/{id}/updateImage', [LaporanController::class, 'updateImage'])->name('laporan.updateImage');


    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;


class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function Role(): HasOne
    {
        return $this->hasOne(role::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Services\Role\RoleServiceInterface;
use App\Services\User\UserServiceInterface;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{
    protected $userService;
    protected $roleService;
    public function __construct(UserServiceInterface $userService, RoleServiceInterface $roleService)
    {
        $this->userService = $userService;
        $this->roleService = $roleService;
    }
    /**
     * Display a listing of the resource.
     */


    public function index()
    {
        if (!Auth::user()->can('read user')) abort(403);

        $users = $this->userService->getAllWithRole();
        return view('user.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        if (!Auth::user()->can('create user')) abort(403);
        $role = $this->roleService->getAll();
        return view('user.create', ['roles' => $role]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(UserStoreRequest $request)
    {
        if (!Auth::user()->can('create user')) abort(403);

        $validRequest = $request->safe()->except(['_token']);
        $validRequest['password'] = Hash::make($validRequest['password']);

        try {
            $this->userService->store($validRequest);
            return redirect()->route('users.index')->with('message', "User berhasil dibuat.");
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['request' => $validRequest]);
            return redirect()->route('users.index')->with('error', "User gagal dibuat.");
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        if (!Auth::user()->can('create user')) abort(403);

        $roles = $this->roleService->getAll();
        $users = $this->userService->getById($id);
        $role = $users->getRoleNames();
        // dd($role[0]);
        return view('user.edit', ['roles' => $roles, 'user' => $users, 'role' => $role]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UserUpdateRequest $request, string $id)
    {
        if (!Auth::user()->can('update user')) abort(403);

        $validRequest = $request->safe()->except(['_token']);

        if ($request->has('password') && $request->password != '') {
            $validRequest['password'] = Hash::make($validRequest['password']);
        }

        // dd($validRequest);

        try {
            $this->userService->update($id, $validRequest);
            return redirect()->route('users.index')->with('message', "User berhasil diubah.");
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['request' => $validRequest]);
            return redirect()->route('users.index')->with('error', "User gagal diubah.");
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

    public function delete(int $id)
    {
        if (!Auth::user()->can('delete user')) abort(403);

        try {
            $this->userService->delete($id);
            return redirect()->route('users.index')->with('message', "User berhasil dihapus.");
        } catch (\Exception $th) {
            Log::error($th->getMessage(), ['user_id' => $id]);
            return redirect()->route('users.index')->with('error', "User gagal dihapus.");
        }
    }
}

resources/views/user/create.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Tambah Users')
@section('page-heading')
  <h1>Tambah Users</h1>
@endsection
@section('content')
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
          @if ($errors->any())
            @foreach ($errors->all() as $err)
              <div class="alert alert-danger">
                  {{$err}}
              </div>
            @endforeach    
          @endif
        <form action="{{route('users.store')}}" class="form" method="POST">
          @csrf
          <div class="form-group row mb-2">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama</label>
            <div class="col-sm-12 col-md-4">
              <input type="text" name="name" class="form-control" value="{{old('name')}}" required>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Email</label>
            <div class="col-sm-12 col-md-4">
                <input type="email" name="email" class="form-control" value="{{old('email')}}" required>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Password</label>
            <div class="col-sm-12 col-md-4">
                <input type="password" name="password" class="form-control" required>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Password Confirmation</label>
            <div class="col-sm-12 col-md-4">
                <input type="password" name="password_confirmation" class="form-control" required>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Role</label>
            <div class="col-sm-12 col-md-2">
                <select name="role" class="form-control" required>
                    <option value="">--- Pilih Role ---</option>
                    @foreach ($roles as $role)
                    <option value="{{$role->name}}">{{$role->name}}</option>
                    @endforeach
                </select>
            </div>
          </div>
          <div class="form-group row mb-4">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
            <div class="col-sm-12 col-md-7">
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Edit Users')
@section('page-heading')
  <h1>Edit Users</h1>
@endsection
@section('content')
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
          @if ($errors->any())
            @foreach ($errors->all() as $err)
              <div class="alert alert-danger">
                  {{$err}}
              </div>
            @endforeach    
          @endif
        <form action="{{route('users.update', $user->id)}}" class="form" method="POST">
          @method('PUT')
          @csrf
          <div class="form-group row mb-2">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama</label>
            <div class="col-sm-12 col-md-4">
              <input type="text" name="name" class="form-control" value="{{old('name') ?? $user->name }}" required>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Email</label>
            <div class="col-sm-12 col-md-4">
                <input type="email" name="email" class="form-control" value="{{old('email') ?? $user->email}}" required>
            </div>
          </div>
          <div class="form-group row mb-2">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Password</label>
            <div class="col-sm-12 col-md-4">
                <input type="password" name="password" class="form-control" >
            </div>
          </div>
          <div class="form-group row mb-2">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Password Confirmation</label>
            <div class="col-sm-12 col-md-4">
                <input type="password" name="password_confirmation" class="form-control" >
            </div>
          </div>
          <div class="form-group row mb-2">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Role</label>
            <div class="col-sm-12 col-md-2">
                <select name="role" class="form-control" required>
                    <option value="">--- Pilih Role ---</option>
                    @foreach ($roles as $item)
                    <option value="{{$item->id}}" {{$role[0] == $item->name ? 'selected':''}}> 
                        {{$item->name}}</option>
                    @endforeach
                </select>
            </div>
          </div>
          <div class="form-group row mb-4">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
            <div class="col-sm-12 col-md-7">
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Users')
@section('page-heading')
  <h1>Users</h1>
@endsection
@section('content')
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body table-responsive">
          <a href="{{route('users.create')}}" class="btn btn-info mb-2">Tambah Data</a>
          @if (session('error'))
            <div class="alert alert-danger">{{session('error')}}</div> 
          @endif
          @if (session('message'))
            <div class="alert alert-primary">{{session('message')}}</div> 
          @endif
          <table class="table table-hover datatable">
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th style="width: 50px">action</th>
              </tr>
            </thead>
            <tbody>
            @foreach ($users as $user)  
                <tr>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->role}}</td>
                    <td>
                        <a href="{{route('users.edit', $user->id)}}" class="btn btn-icon btn-sm btn-warning"><i class="fas fa-edit"></i></a>
                        <a href="{{route('users.delete', $user->id)}}" class="btn btn-icon btn-sm btn-danger"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('page-css')
  <link rel="stylesheet" href="{{asset('assets/modules/DataTables/dt/css/dataTables.bootstrap4.min.css')}}">
@endpush
@push('page-js')
  <script src="{{asset('assets/modules/DataTables/dt/js/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('assets/modules/DataTables/dt/js/dataTables.bootstrap4.min.js')}}"></script>
  <script>
    $(document).ready( function () {
      $('.datatable').DataTable();
    });
  </script>
@endpush