routes/web.php
<?php

use App\Http\Controllers\AgendaController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LampuController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SaranController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login-process', [AuthController::class, 'loginProcess'])->name('login.process');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('/users', UserController::class);
    Route::resource('/laporan', LaporanController::class);
    Route::resource('/lampu', LampuController::class);
    Route::resource('/petugas', PetugasController::class);
    Route::resource('/agenda', AgendaController::class);
    Route::resource('/slider', SliderController::class);



    Route::get('/role', [RoleController::class, 'index'])->name('role.index');
    Route::get('/role/create', [RoleController::class, 'create'])->name('role.create');
    Route::post('/role', [RoleController::class, 'store'])->name('role.store');
    Route::get('/role/{id}/edit', [RoleController::class, 'edit'])->name('role.edit');
    Route::put('/role/{id}/update', [RoleController::class, 'update'])->name('role.update');

    Route::get('/saran', [SaranController::class, 'index'])->name('saran.index');
    Route::get('/saran/create', [SaranController::class, 'create'])->name('saran.create');
    Route::post('/saran', [SaranController::class, 'store'])->name('saran.store');
    Route::get('/saran/{id}/update', [SaranController::class, 'delete'])->name('role.delete');



    // DELETE ROUTE
    Route::get('/user/{id}/delete', [UserController::class, 'delete'])->name('users.delete');
    Route::get('/saran/{id}/delete', [SaranController::class, 'delete'])->name('saran.delete');
    //     Route::get('/lampu/read/file', [LampuController::class, 'readCsv'])->name('lampu.read');
    // Route::get('/laporan/{id}/delete', [LaporanController::class, 'delete'])->name('laporan.delete');

    // CUSTOM ROUTER FOR PUT / PATCH IMAGE FORM
    Route::post('/laporan/{id}/updateImage', [LaporanController::class, 'updateImage'])->name('laporan.updateImage');


    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});

resources/views/layouts/admin-master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <link rel="shortcut icon" href="{{asset('assets/img/favicon.png')}}" type="image/x-icon">
  <link rel="icon" href="{{asset('assets/img/favicon.png')}}" type="image/x-icon">
  <title>@yield('page-title', 'Dashboard') &mdash; {{config('app.name')}}</title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <!-- CSS Libraries -->
    @stack('page-css')
  <!-- Template CSS -->
  <link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
  <link rel="stylesheet" href="{{asset('assets/css/components.css')}}">
    
</head>

<body>
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
          </ul>
        </form>
        @include('layouts.topbar')
      </nav>
      @include('layouts.sidebar')

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            {{-- <h1>@yield('page-heading','Blank Page')</h1> --}}
            @yield('page-heading','Blank Page')
          </div>

          <div class="section-body">
              @yield('content')
          </div>
        </section>
      </div>
      @stack('modal')
      @include('layouts.footer')
    </div>
  </div>

  <!-- General JS Scripts -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="{{asset('assets/js/stisla.js')}}"></script>

  <!-- JS Libraies -->

  <!-- Template JS File -->
  <script src="{{asset('assets/js/scripts.js')}}"></script>
  {{-- <script src="{{asset('assets/js/custom.js')}}"></script> --}}

  <!-- Page Specific JS File -->
  @stack('page-js')
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
      Copyright &copy; 2023 <div class="bullet"></div> {{config('app.name')}} <a href="{{route('dashboard')}}" target="_blank"> | DINAS PERHUBUNGAN KOTA SINGKAWANG</a>
    </div>
    <div class="footer-right">
      V 1.0
    </div>
</footer>

resources/views/layouts/sidebar.blade.php
<div class="main-sidebar">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <a href="{{route('dashboard')}}"><img class="mr-1" src="{{asset('assets/img/logo-dishub.png')}}" alt="Logo Pemkot Singkawang" srcset="" height="50px">
        {{config('app.name')}}
      </a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <a href="{{route('dashboard')}}">
        <img src="{{asset('assets/img/logo-dishub.png')}}" alt="Logo Pemkot" srcset="" height="50px">
      </a>
    </div>
    <ul class="sidebar-menu">
      <li class="{{set_active('dashboard')}}"><a class="nav-link" href="{{ route('dashboard') }}"><i class="fas fa-laptop"></i><span>Dashboard</span></a></li>

      @can("read user")
      <li class="menu-header">Transaction Data</li>
      @endcan

      @can("read laporan")
      <li class="{{set_active('laporan.*')}}"><a class="nav-link" href="{{ route('laporan.index') }}"><i class="fas fa-bullhorn"></i><span>Laporan</span></a></li>
      @endcan

      @can("read saran")
      <li class="{{set_active('saran.*')}}"><a class="nav-link" href="{{ route('saran.index') }}"><i class="far fa-comments"></i><span>Masukan & Saran</span></a></li>
      @endcan

        @can("read agenda")
            <li class="{{set_active('agenda.*')}}"><a class="nav-link" href="{{ route('agenda.index') }}"><i class="far fa-calendar-alt"></i><span>Agenda</span></a></li>
        @endcan


      @can("read user")
      <li class="menu-header">Master Data</li>
      @endcan

      @can("read lampu")
      <li class="{{set_active('lampu.*')}}"><a class="nav-link" href="{{ route('lampu.index') }}"><i class="far fa-lightbulb"></i><span>Lampu</span></a></li>
      @endcan

      @can("read petugas")
      <li class="{{set_active('petugas.*')}}"><a class="nav-link" href="{{ route('petugas.index') }}"><i class="fas fa-street-view"></i><span>petugas</span></a></li>
      @endcan

        @can("read slider")
            <li class="{{set_active('slider.*')}}"><a class="nav-link" href="{{ route('slider.index') }}"><i class="far fa-images"></i><span>Slider</span></a></li>
        @endcan
      @can("read user")
      <li class="{{set_active('users.*')}}"><a class="nav-link" href="{{ route('users.index') }}"><i class="far fa-user"></i><span>Users</span></a></li>
      @endcan

      @can("read role")
      <li class="{{set_active('role.*')}}"><a class="nav-link" href="{{ route('role.index') }}"><i class="fas fa-user-tag"></i><span>Role</span></a></li>
      @endcan
    </ul>
    <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
      <a href="{{ route('logout') }}" class="btn btn-danger btn-lg btn-block btn-icon-split">
        <i class="fas fa-sign-out-alt"></i> Logout
      </a>
    </div>
  </aside>
</div>

resources/views/layouts/topbar.blade.php
@php
    $carbon = new Carbon\Carbon;
@endphp
<ul class="navbar-nav navbar-right">
    <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
    <img alt="image" src="{{asset('assets/img/avatar/avatar-1.png')}}" class="rounded-circle mr-1">
      <div class="d-sm-none d-lg-inline-block">Hi, {{ (auth()->user()) ? auth()->user()->name : ''}}</div></a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-title">Login {{$carbon->diffForHumans(session('login_time'))}}</div>
        <div class="dropdown-divider"></div>
        <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger">
          <i class="fas fa-sign-out-alt"></i> Logout
        </a>
      </div>
    </li>
  </ul>